package io.genreadme.service;

import io.genreadme.model.ProjectInfo;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.Map;

/**
 * Service for GitLab API integration
 */
@Service
@Slf4j
public class GitLabScannerService {
    
    @Value("${gitlab.token:}")
    private String gitlabToken;
    
    private final RestTemplate restTemplate = new RestTemplate();
    
    public ProjectInfo analyzeProject(String repositoryUrl) {
        log.info("Analyzing GitLab project: {}", repositoryUrl);
        
        try {
            // Extract project info from URL
            String[] parts = repositoryUrl.replace("https://gitlab.com/", "").replace("https://github.com/", "").split("/");
            String namespace = parts[0];
            String projectName = parts[1];
            String projectPath = namespace + "/" + projectName;
            String apiUrl ;
            if(repositoryUrl.contains("github")) {
            	 apiUrl = "https://api.github.com/repos/" + projectPath;

            }
            else{// Get project details from GitLab API
             apiUrl = "https://gitlab.com/api/v4/projects/" + 
                           java.net.URLEncoder.encode(projectPath, "UTF-8");
            }
            HttpHeaders headers = new HttpHeaders();
            if (!gitlabToken.isEmpty()) {
                headers.set("Authorization", "Bearer " + gitlabToken);
            }
            
            HttpEntity<String> entity = new HttpEntity<>(headers);
            Map<String, Object> projectData = restTemplate.exchange(
                apiUrl, HttpMethod.GET, entity, Map.class
            ).getBody();
            
            // Analyze project structure and dependencies
            return ProjectInfo.builder()
                .name(projectName)
                .description((String) projectData.get("description"))
                .url(repositoryUrl)
                .language(detectPrimaryLanguage(projectPath))
                .techStack(detectTechStack(projectPath))
                .type(detectProjectType(projectPath))
                .complexity(calculateComplexity(projectData))
                .quality(8.5) // Default quality score
                .build();
                
        } catch (Exception e) {
            log.error("Failed to analyze project: {}", repositoryUrl, e);
            // Return basic project info as fallback
            return createFallbackProjectInfo(repositoryUrl);
        }
    }
    
    public String createReadmeMergeRequest(String repositoryUrl, String readmeContent) {
        log.info("Creating merge request for README update");
        
        try {
            // Extract project path
            String projectPath = repositoryUrl.replace("https://gitlab.com/", "");
            String apiUrl = "https://gitlab.com/api/v4/projects/" + 
                           java.net.URLEncoder.encode(projectPath, "UTF-8") + "/merge_requests";
            
            // Create merge request payload
            Map<String, Object> mrData = Map.of(
                "source_branch", "feature/ai-generated-readme",
                "target_branch", "main",
                "title", "AI-Generated README Documentation",
                "description", "Intelligent README generated by GenREADME AI system"
            );
            
            HttpHeaders headers = new HttpHeaders();
            headers.set("Authorization", "Bearer " + gitlabToken);
            headers.set("Content-Type", "application/json");
            
            HttpEntity<Map<String, Object>> entity = new HttpEntity<>(mrData, headers);
            Map<String, Object> response = restTemplate.postForObject(apiUrl, entity, Map.class);
            
            return (String) response.get("web_url");
            
        } catch (Exception e) {
            log.error("Failed to create merge request", e);
            return null;
        }
    }
    
    private String detectPrimaryLanguage(String projectPath) {
        // Simplified language detection - in production, analyze actual files
        if (projectPath.contains("spring") || projectPath.contains("java")) return "Java";
        if (projectPath.contains("react") || projectPath.contains("node")) return "JavaScript";
        if (projectPath.contains("python") || projectPath.contains("django")) return "Python";
        return "Unknown";
    }
    
    private String detectTechStack(String projectPath) {
        // Simplified tech stack detection
        if (projectPath.contains("spring")) return "Spring Boot + Java";
        if (projectPath.contains("react")) return "React + Node.js";
        if (projectPath.contains("django")) return "Django + Python";
        return "Modern Web Stack";
    }
    
    private String detectProjectType(String projectPath) {
        if (projectPath.contains("microservice") || projectPath.contains("api")) return "Microservice";
        if (projectPath.contains("frontend") || projectPath.contains("ui")) return "Frontend Application";
        if (projectPath.contains("ml") || projectPath.contains("data")) return "Data Science";
        return "Web Application";
    }
    
    private double calculateComplexity(Map<String, Object> projectData) {
        // Simple complexity calculation based on project metrics
        int stars = (Integer) projectData.getOrDefault("star_count", 0);
        int forks = (Integer) projectData.getOrDefault("forks_count", 0);
        
        if (stars > 100 || forks > 20) return 9.0;
        if (stars > 50 || forks > 10) return 7.5;
        if (stars > 10 || forks > 5) return 6.0;
        return 5.0;
    }
    
    private ProjectInfo createFallbackProjectInfo(String repositoryUrl) {
        String projectName = repositoryUrl.substring(repositoryUrl.lastIndexOf("/") + 1);
        return ProjectInfo.builder()
            .name(projectName)
            .description("AI-analyzed project")
            .url(repositoryUrl)
            .language("Java")
            .techStack("Spring Boot + Modern Stack")
            .type("Web Application")
            .complexity(7.0)
            .quality(8.0)
            .build();
    }
}